<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>EachItemOnWishListPage</name>
   <tag></tag>
   <elementGuidId>12553ad0-4fe7-47b6-90d0-263d3be64632</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//strong[@class='product-item-name']/a)[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
