<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>AddToCompare</name>
   <tag></tag>
   <elementGuidId>bc683b27-d0eb-4747-9377-1d72ea0ed5cc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='layer-product-list']/div[7]/div/div[&quot;+i+&quot;]/div/div[3]/div[2]/div/label
</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
